# Make x86-64 random byte generators.

# Copyright 2015, 2020, 2021 Paul Eggert

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.  */



# The source files
FILES = $(wildcard *.c) $(wildcard *.h)

# Optimization level.  Change this -O2 to -Og or -O0 or whatever.
OPTIMIZE =

# The C compiler and its options.
CC = gcc
CFLAGS = $(OPTIMIZE) -g3 -Wall -Wextra -fanalyzer \
  -march=native -mtune=native -mrdrnd

# The archiver command, its options and filename extension.
TAR = tar
TARFLAGS = --gzip --transform 's,^,randall/,'
TAREXT = tgz

default: randall

randall: randall.c $(FILES)
	$(CC) $(CFLAGS) *.c -o $@

#implementation of the make check
check: randall
	@echo "Running test cases"
	@echo "=============== TEST 1 ================="
	@echo "----Test that the number of randomly generated bytes produced by randall is correct----"
	@./randall 40 | wc -c | grep -q '^40$$' || (echo "Output length test failed" && false)
	@echo "Tests for output length are passed."
	
	
	@echo "=============== TEST 2 ================="
	@echo "----Testing the length of the ouput for -i lrand48_r----"
	@./randall -i lrand48_r 8 | wc -c | grep -q '^8$$' \
		|| (echo "Output length test failed" && false)
	@./randall 50 > testCases.out
	@if [ $$(wc -c < testCases.out) -eq 50 ]; then \
	echo "Test for lrand length was passed"; \
	else \
	echo "Test for lrand length failed"; \
	exit 1; \
	fi


	@echo "=============== TEST 3 ================="
	@echo "----Testing the length of the output for ldrand when passed with N bytes ----"
	@./randall -i lrand48_r -o 40 20 > test.out
	@if [ $$(wc -c < test.out) -eq 20 ]; then \
	echo "Test passed for lrand N bytes"; \
	else \
	echo "Test failed for lrand N bytes"; \
	exit 1; \
	fi



	@echo "=============== TEST 4 ================="
	@echo "----Testing ldrand48_r length of output when passed with stdio option----"	
		@./randall -i lrand48_r 99  > test.out
	@if [ $$(wc -c < test.out) -eq 99 ]; then \
	echo "Test passed for lrand stdio"; \
	else \
	echo "Test failed for lrand stdio"; \
	exit 1; \
	fi

	@echo "=============== Passed all tests ==============="



# Automatically formats all of your C code.
format:
	clang-format -i *.c *.h
# Helps find memory leaks. For an explanation on each flag, see this link.
valgrind: randall
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./randall 100
# Runs the Undefined Behavior (UBSAN) and Address (ASAN) sanitizers. GCC doesn’t support these on the SEASNet servers so we recommend using clang instead (a different C compiler).
sanitizers:
	clang -g3 -Wall -Wextra -mtune-native -mrdrnd -fsanitize=address \
		-fsanitize=undefined *.c -o randall

# Make sure to add these rules to .PHONY. These tells make that it should not look for files called each of these recipe targets.
.PHONY: default clean assignment submission-tarball repository-tarball check format valgrind sanitizers



assignment: randall-assignment.$(TAREXT)
assignment-files = COPYING Makefile $(FILES)
randall-assignment.$(TAREXT): $(assignment-files)
	$(TAR) $(TARFLAGS) -cf $@ $(assignment-files)

submission-tarball: randall-submission.$(TAREXT)
submission-files = $(assignment-files) \
  notes.txt # More files should be listed here, as needed.
randall-submission.$(TAREXT): $(submission-files)
	$(TAR) $(TARFLAGS) -cf $@ $(submission-files)

repository-tarball:
	$(TAR) -czf randall-git.tgz .git


clean:
	rm -f *.o *.$(TAREXT) randall
